SELC-2668
pagopa/selfcare-dashboard-backend pull request #230
Opened 2023-07-24 10:20 UTC by empassaro

2023-07-24 12:20 UTC, manuraf commented
Title and description don't follow our convention template (https://github.com/pagopa/selfcare-dashboard-backend/blob/main/.github/PULL_REQUEST_TEMPLATE.md). For example, look at https://github.com/pagopa/selfcare-ms-core/pull/144

2023-07-24 12:20 UTC, manuraf requested changes
Title and description don't follow our convention template (https://github.com/pagopa/selfcare-dashboard-backend/blob/main/.github/PULL_REQUEST_TEMPLATE.md). For example, look at https://github.com/pagopa/selfcare-ms-core/pull/144

2023-07-28 12:59 UTC, andrea-putzu approved these changes

2023-07-31 06:50 UTC, manuraf approved these changes

2023-07-31 07:16 UTC, merged