SELC-2411 Refactor Api GetInstitution in InstitutionController
pagopa/selfcare-dashboard-backend pull request #244
Opened 2023-08-03 07:55 UTC by flaminiaScarciofolo

#### List of Changes

Refactor Api GetInstitution in InstitutionController

#### Motivation and Context

#### How Has This Been Tested?

2023-08-03 09:20 UTC, manuraf requested changes

2023-08-03 09:20 UTC, manuraf commented on web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionMapperTest.java
> +        InstitutionResource institutionResource = InstitutionMapper.toResource((InstitutionInfo) null);
using the mapstruct mapper we can avoid doing unit tests on InstitutionMapperTest

2023-08-09 08:20 UTC, KevinSi96 approved these changes

2023-08-09 08:21 UTC, andrea-putzu approved these changes

2023-08-09 08:22 UTC, merged