[SELC-4202] Feat: Added Api V2 for
pagopa/selfcare-dashboard-backend pull request #377
Opened 2024-03-18 14:59 UTC by flaminiaScarciofolo

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-18 16:04 UTC, pierpaolodidato89 commented on connector/azure-storage/pom.xml
> +        <dependency>
Why do we need these dependencies here?

2024-03-19 08:29 UTC, manuraf requested changes

2024-03-19 08:29 UTC, manuraf commented on core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImpl.java
> +                });
it might be better that frontend retrieve this information itself....

2024-03-19 08:29 UTC, manuraf commented on web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2Controller.java
> +        InstitutionUserDetailsResource result = UserMapper.toInstitutionUserDetails(userInfo);
you could use mapstruct for construct a mapper

2024-03-19 16:29 UTC, manuraf approved these changes

2024-03-19 16:30 UTC, merged